// ============================================================
// GAME STATE
// ============================================================

const SEAT_WINDS = ["east", "south", "west", "north"];
const SEAT_LABELS = ["East (You)", "South (AI)", "West (AI)", "North (AI)"];

// Match-scope identifier (spec §6.4). Created once per match in
// createInitialState; persists across rounds; not regenerated by
// initRound. Used by lifetime stats, achievements, replay linkage,
// and resume-SFX suppression. The padEnd is load-bearing — see §6.4.
function makeGameId() {
  if (globalThis.crypto?.randomUUID) return globalThis.crypto.randomUUID();
  const t = Date.now().toString(36);
  const r = Math.random().toString(36).slice(2).padEnd(8, "0");
  return `${t}-${r}`;
}

// createInitialState now takes a seed and optional daily metadata (spec
// §9.6). Match-scope matchSeed is derived from the supplied seed or a
// fresh randomUint32; round-1 seed is derived deterministically from it.
function createInitialState(windRounds = 1, lang = "en", seed, opts = {}) {
  const { dailyDate = null } = opts;
  const isDaily = !!dailyDate;
  const matchSeed = ((seed !== undefined ? seed : randomUint32()) >>> 0);
  // cosmeticRng drives personality + name selection so daily games are
  // identical across users even if local custom name groups vary.
  // deckRng (in initRound) is separately derived from the round seed.
  const cosmeticRng = seededRng((matchSeed ^ 0x9E3779B9) >>> 0);
  const personalities = assignPersonalities(cosmeticRng);
  // Daily mode uses the fixed DAILY_NAME_GROUPS (spec §9.7); normal
  // games use the user's loaded groups.
  const nameGroups = isDaily ? DAILY_NAME_GROUPS : loadNameGroups();
  const { groupName, names } = pickPlayerNames(nameGroups, 4, cosmeticRng);
  // Phase 7 (§11.4.1) — freeze one line index per seat per reaction kind
  // so each AI always says the same thing on its first hu of a given
  // match, and so daily games have deterministic dialogue across users.
  const reactionSeeds = seedReactionIndices(cosmeticRng);
  const totalRounds = windRounds * 4;
  const startingScore = totalRounds * STARTING_PER_ROUND;
  const round1Seed = seedForRound(matchSeed, 1);
  return initRound({
    dealer: 0,
    roundWind: "east",
    roundNumber: 1,
    totalRounds,
    windRounds,
    scores: [startingScore, startingScore, startingScore, startingScore],
    roundResults: [],
    personalities,
    playerNames: names,
    nameGroup: groupName,
    // Match-scope hint usage flag (spec §5.3). Lives here, not in
    // initRound, because nextRound spreads prev → gameInfo and we want
    // this flag to carry through round transitions.
    hintUsedThisGame: false,
    // Match-scope resume/replay metadata (spec §6.4, §6.6, §6.2). Same
    // placement reason as hintUsedThisGame above — must survive
    // round transitions via nextRound's prev-spread.
    gameId: makeGameId(),
    persistRev: 0,
    adminTouched: false,
    // Phase 5 seed/daily metadata (spec §9.5, §9.8).
    matchSeed,
    roundSeeds: { 1: round1Seed },
    dailyGame: isDaily,
    dailyDate,
    // Phase 7 (§11.4.1) match-scope seed indices for AI reaction lines.
    reactionSeeds,
    // Per Appendix A.6 / spec §9.4 — track admin-minted tile ids at
    // match scope so they're never reused within a match.
    usedAdminIds: [],
  }, lang, round1Seed);
}

function initRound(gameInfo, lang = "en", roundSeed) {
  const ll = LANG[lang];
  const deckRng = seededRng(roundSeed >>> 0);
  const deck = shuffle(createDeck(), deckRng);
  const players = [];
  for (let i = 0; i < 4; i++) {
    players.push({
      hand: sortHand(deck.splice(0, 13)),
      openMelds: [],
      discards: [],
      seatWind: SEAT_WINDS[(i - gameInfo.dealer + 4) % 4],
    });
  }
  players[gameInfo.dealer].hand.push(deck.splice(0, 1)[0]);
  players[gameInfo.dealer].hand = sortHand(players[gameInfo.dealer].hand);

  return {
    ...gameInfo,
    players,
    wall: deck,
    currentTurn: gameInfo.dealer,
    phase: "discard",
    lastDiscard: null,
    lastDiscarder: null,
    claims: [],
    winner: null,
    winInfo: null,
    scoreBreakdown: null,
    isDraw: false,
    log: [ll.logRoundBegin(gameInfo.roundNumber, ll.seats[gameInfo.dealer])],
    // Phase 9a §13.5 — machine-readable action log, one entry per
    // action-emitting handler. Reset per round; nextRound spreads
    // prev into gameInfo but this explicit field overwrites it, so
    // each round starts with an empty log.
    actionLog: [],
    pendingClaims: null,
    selectedTile: null,
    awaitingPlayerClaim: null,
    playerDeclinedClaims: [],
    turnDrawn: true,
    lastDrawn: null,
  };
}

