// ============================================================
// LOCALIZATION
// ============================================================

const LANG = {
  en: {
    tileName: (t) => {
      if (t.suit === "wind") return `${t.honor} wind`;
      if (t.suit === "dragon") return `${t.honor} dragon`;
      return `${t.rank} ${t.suit}`;
    },
    seats: ["East (You)", "South (AI)", "West (AI)", "North (AI)"],
    seatsShort: ["You", "South", "West", "North"],
    windDisplay: (w) => ({ east: "East", south: "South", west: "West", north: "North" }[w]),
    actionLabel: { chi: "Chi", peng: "Peng", gang: "Gang", hu: "Hu" },
    // Menu
    title: "🀄 Mahjong", subtitle: "House Rules Edition",
    windRoundsLabel: "Wind Rounds:",
    windRoundsBtn: (n) => `${n} (${n * 4} rounds)`,
    startGame: "Start Game", langToggle: "中文",
    resumeGame: "▶ Resume Game",
    resumeNote: "Resuming keeps the saved game's settings.",
    difficultyLabel: "AI Difficulty:",
    diffEasy: "Easy", diffMedium: "Medium", diffExpert: "Expert",
    trainingModeLabel: "Training Mode (hints on your turn)",
    aiReactionsLabel: "AI Reactions (bubbles above opponents)",
    hintBtn: "💡 Hint",
    hintBestTag: "↑ best",
    setupLabel: "Setup",
    setupRoundsFmt: (n) => `${n} rounds`,
    setupTrainOn: "Training on",
    setupTrainOff: "Training off",
    setupEditBtn: "✏️ Edit",
    setupDoneBtn: "✓ Done",
    // Personalities
    pGeneric: "Standard", pAggressive: "Aggressive", pDefensive: "Defensive", pAdaptive: "Adaptive",
    rulesTitle: "House Rules",
    rule1: "1. All three suits must be represented",
    rule2: "2. At least one meld must have a terminal (1/9) or honor tile",
    rule3: "3. Must have at least one open meld (claimed from discard)",
    rule4: "4. Seven Pairs: 7 concealed pairs wins (rules 1 & 2 apply, rule 3 waived)",
    // Top bar
    roundInfo: (num, total, wind) => `Round ${num}/${total} · ${wind} Wind`,
    wallCount: (n) => `🧱 ${n}`,
    turnOther: (name) => `${name}'s turn`,
    turnDraw: "Your turn — draw a tile",
    turnDiscard: "Your turn — select a tile to discard",
    // Discard pool
    poolTitle: "Discard Pool", latest: "Latest:",
    // Actions
    drawTile: "🎴 Draw Tile", discardSel: "✕ Discard Selected",
    declareHu: "🀄 Declare Hu!",
    gangBtn: (name) => `Gang (${name})`,
    // Claim
    discardedBy: (name) => `${name} discarded `,
    youCan: "You can ", winRound: " — Win the round!",
    pass: "Pass", claimBtn: (type) => `Claim ${type}`,
    huBtn: "🀄 Hu!",
    // Round over
    youWin: "🎉 You Win!", otherWins: (name) => `${name} Wins!`,
    drawExhausted: "Draw — Wall Exhausted", winHand: "Winning hand:", winningTile: "Winning tile",
    sevenPairs: "Seven Pairs (七小对)",
    gameComplete: "Game Complete!", backMenu: "Back to Menu", nextRound: "Next Round →",
    tabWinner: "Who Won", tabScoring: "Scoring", tabStats: "Stats",
    tabStandings: "Standings",
    scoringNoExchange: "No points exchanged.",
    gameSummary: "Game Summary →",
    gameOverTitle: "🏆 Game Over",
    finalStandings: "Final Standings",
    rankSuffix: (n) => ({1:"st",2:"nd",3:"rd"})[n] || "th",
    // Stats — round
    roundStatsTitle: "Round Stats",
    roundHeader: (n, total, wind, dealer) => `Round ${n} of ${total} · ${wind} prevailing · Dealer: ${dealer}`,
    wallRemainingLabel: "Wall remaining",
    standingsNow: "Current Standings",
    winnerPersonality: "Winner's style",
    // Stats — game
    playerStatsTitle: "Per-player Stats",
    statWins: "Wins",
    statDianpao: "Dianpao given",
    statBiggestGain: "Biggest gain",
    statBiggestLoss: "Biggest loss",
    statSmallHu: "Small Hu",
    statLargeHu: "Large Hu",
    statZimo: "Zimo",
    statSevenPairs: "7 Pairs",
    historyTitle: "Round History",
    historyDraw: "Draw",
    historyZimo: "Zimo",
    historyDianpao: (name) => `Dianpao from ${name}`,
    bestRoundLabel: "Biggest single haul",
    bestRoundLine: (name, amt, n) => `${name} +${amt} in Round ${n}`,
    bankruptcyTitle: "Bankruptcy",
    bankruptcyLine: (name, n) => `${name} went broke at Round ${n}`,
    noBankruptcy: "Nobody went broke.",
    open: "open", hidden: "hidden", tiles: "tiles",
    turnOrder: "Counter-clockwise",
    posLeft: "← Left", posRight: "Right →", posAcross: "Across",
    // Scoring
    scoreLabel: "Pts",
    smallHu: "Small Hu", largeHu: "Large Hu",
    winTypeZimo: "Zimo (self-draw)", winTypeDianpao: "Dianpao (off discard)",
    breakdownTitle: "Scoring",
    baseLabel: "Base",
    modNoOpen: "No open meld",
    modDianpao: "Gave winning tile",
    modZimo: "Zimo",
    modSevenPairs: "Seven Pairs",
    winnerGains: (n) => `Winner +${n}`,
    loserLoses: (mult, loss) => `×${mult} = -${loss}`,
    // Log messages
    logRoundBegin: (n, d) => `Round ${n} begins. ${d} is dealer.`,
    logExhaust: "Wall exhausted — draw!",
    logGangConc: (n, t) => `${n} declares concealed Gang of ${t}.`,
    logZimo: (n, t) => `${n} draws ${t} and wins by Zimo!`,
    logDraw: (n) => `${n} draws a tile.`,
    logDiscard: (n, t) => `${n} discards ${t}.`,
    logDianpao: (n, t) => `${n} claims ${t} and wins by Dianpao!`,
    logClaim: (n, t, ty) => `${n} claims ${t} for ${ty}.`,
    logYouDraw: (t) => `You draw ${t}.`,
    logCanHu: "You can declare Hu (Zimo)!",
    logYouDiscard: (t) => `You discard ${t}.`,
    logYouHu: "You declare Hu by Zimo!",
    logBadHu: "Your hand is not a valid Hu.",
    logYouGang: (t) => `You declare concealed Gang of ${t}. Drew replacement tile.`,
    logYouPromotedGang: (t) => `You promote Peng to Gang of ${t}. Drew replacement tile.`,
    logPromotedGang: (n, t) => `${n} promotes Peng to Gang of ${t}.`,
    promotedGangBtn: (name) => `+ Gang (${name})`,
    logOver: "Game over!",
    howToPlay: "How to Play",
    helpClose: "✕ Close",
    // Admin console
    adminMenuBtn: "🔧 Admin",
    adminBtn: "🔧",
    adminTitle: "Admin Console",
    adminClose: "✕ Close",
    adminLegend: "Tiles: b1–b9 (bamboo) · c1–c9 (characters) · d1–d9 (dots) · E S W N (winds) · R G P (red/green/white dragon). Melds: type:tile tile tile (add ! after type for concealed). Multiple melds separated by ;.",
    adminMeldExample: "Example: peng:c5 c5 c5; chi:b1 b2 b3; gang!:d7 d7 d7 d7",
    adminTurn: "Turn",
    adminPhase: "Phase",
    adminWall: "Wall (next tiles)",
    adminScore: "Score",
    adminHand: "Hand",
    adminMelds: "Open Melds",
    adminDiscards: "Discards",
    adminCancel: "Cancel",
    adminApply: "Apply",
    adminPhaseDraw: "Draw",
    adminPhaseDiscard: "Discard",
    adminPhaseClaim: "Claim",
    adminTabState: "State", adminTabNames: "Names",
    // AI names list
    manageNamesBtn: "Manage Names",
    manageNamesTitle: "AI Player Names",
    namesHint: "Three names are picked at random at the start of each game. List is saved to your browser.",
    addNamePlaceholder: "Add a name",
    addNameBtn: "+ Add",
    addGroupPlaceholder: "New group name",
    addGroupBtn: "+ Group",
    resetNamesBtn: "Reset to defaults",
    namesEmpty: "No groups yet — add one or reset to defaults.",
    groupEmpty: "No names in this group.",
    // Stats modal (spec §7.6)
    statsBtn: "📊 Stats",
    setupTitle: "Game Setup",
    statsTitle: "Lifetime Stats",
    statsClose: "✕ Close",
    statsSectionGames: "Games",
    statsSectionWins: "Wins & Hu",
    statsSectionRecords: "Records",
    statsSectionStreaks: "Streaks",
    statsResetBtn: "Reset Stats",
    statsResetConfirm: "Reset all lifetime stats? This cannot be undone.",
    statsResetAchievementsBtn: "Reset Achievements",
    statsResetAchievementsConfirm: "Reset all unlocked achievements? This cannot be undone.",
    // Achievements (spec §8)
    statsSectionAchievements: "Achievements",
    statsTabStats: "Stats",
    statsTabAchievements: "Achievements",
    achToastUnlocked: (name) => `🏆 Achievement Unlocked: ${name}`,
    achUnlockedAt: (date) => `Unlocked ${date}`,
    achLocked: "Locked",
    achFirstHuName: "First Hu",
    achFirstHuDesc: "Win your first round.",
    achFirstLargeHuName: "Big Win",
    achFirstLargeHuDesc: "Win a round by Large Hu.",
    achFirstSevenPairsName: "Seven Pairs",
    achFirstSevenPairsDesc: "Win a round by Seven Pairs.",
    achFirstZimoName: "Self-Drawn",
    achFirstZimoDesc: "Win a round by Zimo.",
    achWins10Name: "Veteran",
    achWins10Desc: "Win 10 games.",
    achWins50Name: "Master",
    achWins50Desc: "Win 50 games.",
    achNoClaimWinName: "Self-Made",
    achNoClaimWinDesc: "Win a round without claiming any discards.",
    achBankruptTableName: "Bankrupt Table",
    achBankruptTableDesc: "End a game with all 3 opponents in the negative.",
    achLastTileName: "Last Tile",
    achLastTileDesc: "Win Hu on the very last wall tile.",
    achComebackKidName: "Comeback Kid",
    achComebackKidDesc: "Win after being lowest (or tied-lowest) for half the rounds.",
    achStreak5Name: "On Fire",
    achStreak5Desc: "Win 5 games in a row.",
    achPuristName: "Purist",
    achPuristDesc: "Win a game without using a single hint.",
    achDailyWin1Name: "Daily Debut",
    achDailyWin1Desc: "Win your first Daily Challenge.",
    achDailyWinStreak7Name: "Week Warrior",
    achDailyWinStreak7Desc: "Win 7 Daily Challenges in a row (consecutive UTC days).",
    // Daily challenge (spec §9.9)
    dailyChallengeBtn: "🗓 Daily",
    dailyChallengeTitle: "Daily Challenge",
    dailyToday: "Today (UTC)",
    dailyResultLabel: "Result",
    dailyStreakLabel: "Streak",
    dailyDaysFmt: (n) => `${n} day${n === 1 ? "" : "s"}`,
    dailyWon: "WON",
    dailyLost: "LOST",
    dailyResetIn: (h, m) => `Next puzzle in ${h}h ${m}m`,
    dailyAlreadyPlayed: "Today's daily has been played.",
    dailyNotPlayed: "Today's daily is available.",
    dailyResultWon: "Result: WON",
    dailyResultLost: "Result: LOST",
    dailyFinalScore: (n) => `Final score: ${n}`,
    dailyRank: (r) => `Rank: ${r}`,
    dailyStreak: (n) => `Current streak: ${n} day${n === 1 ? "" : "s"}`,
    dailyStartBtn: "Start Daily",
    dailyReplayBtn: "Play Again (not recorded)",
    dailyClose: "✕ Close",
    dailyNote: "Daily uses fixed settings (Expert · 1 wind round · no hints) and a UTC-based seed shared by all players.",
    lblGamesPlayed: "Games played",
    lblGamesWon: "Games won",
    lblWinRate: "Win rate",
    lblRoundsPlayed: "Rounds played",
    lblRoundsWon: "Rounds won by Hu",
    lblRoundsDianpao: "Dianpao given",
    lblSmallHu: "Small Hu",
    lblLargeHu: "Large Hu",
    lblZimoHu: "Zimo wins",
    lblSevenPairsHu: "Seven Pairs wins",
    lblBiggestGain: "Biggest single-round gain",
    lblBiggestLoss: "Biggest single-round loss",
    lblBestBalance: "Best ending balance",
    lblWorstBalance: "Worst ending balance",
    lblTotalNet: "Net score (lifetime)",
    lblCurrentStreak: "Current win streak",
    lblLongestStreak: "Longest win streak",
    statsEmDash: "—",
  },
  zh: {
    tileName: (t) => {
      const s = { bamboo: "条", characters: "万", dots: "饼" };
      const w = { east: "东风", south: "南风", west: "西风", north: "北风" };
      const d = { red: "红中", green: "发财", white: "白板" };
      const n = ["", "一", "二", "三", "四", "五", "六", "七", "八", "九"];
      if (t.suit === "wind") return w[t.honor];
      if (t.suit === "dragon") return d[t.honor];
      return `${n[t.rank]}${s[t.suit]}`;
    },
    seats: ["东（你）", "南（电脑）", "西（电脑）", "北（电脑）"],
    seatsShort: ["你", "南", "西", "北"],
    windDisplay: (w) => ({ east: "东", south: "南", west: "西", north: "北" }[w]),
    actionLabel: { chi: "吃", peng: "碰", gang: "杠", hu: "胡" },
    title: "🀄 麻将", subtitle: "自定义规则版",
    windRoundsLabel: "风圈数：",
    windRoundsBtn: (n) => `${n}圈（${n * 4}局）`,
    startGame: "开始游戏", langToggle: "EN",
    resumeGame: "▶ 继续游戏",
    resumeNote: "继续游戏将沿用存档的设置。",
    difficultyLabel: "电脑难度：",
    diffEasy: "简单", diffMedium: "中等", diffExpert: "专家",
    trainingModeLabel: "训练模式（你的回合提示）",
    aiReactionsLabel: "AI反应气泡（对手上方）",
    hintBtn: "💡 提示",
    hintBestTag: "↑ 推荐",
    setupLabel: "设置",
    setupRoundsFmt: (n) => `${n}局`,
    setupTrainOn: "训练开",
    setupTrainOff: "训练关",
    setupEditBtn: "✏️ 编辑",
    setupDoneBtn: "✓ 完成",
    pGeneric: "普通", pAggressive: "激进", pDefensive: "保守", pAdaptive: "随机应变",
    rulesTitle: "自定义规则",
    rule1: "一、手牌须包含条、万、饼三种花色",
    rule2: "二、至少一组牌含幺九牌或字牌",
    rule3: "三、须有至少一组明牌（吃、碰、杠）",
    rule4: "四、七小对：七组暗对可胡（需满足规则一、二，规则三免除）",
    roundInfo: (num, total, wind) => `第${num}/${total}局 · ${wind}风`,
    wallCount: (n) => `🧱 ${n}`,
    turnOther: (name) => `${name}出牌中`,
    turnDraw: "你的回合 — 摸牌",
    turnDiscard: "你的回合 — 选牌打出",
    poolTitle: "牌河", latest: "最新：",
    drawTile: "🎴 摸牌", discardSel: "✕ 打出",
    declareHu: "🀄 胡牌！",
    gangBtn: (name) => `杠（${name}）`,
    discardedBy: (name) => `${name}打出了 `,
    youCan: "你可以", winRound: " — 赢得本局！",
    pass: "过", claimBtn: (type) => `${type}`,
    huBtn: "🀄 胡！",
    youWin: "🎉 你赢了！", otherWins: (name) => `${name}赢了！`,
    drawExhausted: "流局 — 牌墙摸完", winHand: "赢牌：", winningTile: "胡的牌",
    sevenPairs: "七小对",
    gameComplete: "游戏结束！", backMenu: "返回主菜单", nextRound: "下一局 →",
    tabWinner: "胜者", tabScoring: "结算", tabStats: "统计",
    tabStandings: "排名",
    scoringNoExchange: "无分数变化。",
    gameSummary: "总结 →",
    gameOverTitle: "🏆 游戏结束",
    finalStandings: "最终排名",
    rankSuffix: () => "",
    roundStatsTitle: "本局统计",
    roundHeader: (n, total, wind, dealer) => `第${n}局，共${total}局 · ${wind}风 · 庄家：${dealer}`,
    wallRemainingLabel: "牌墙剩余",
    standingsNow: "当前排名",
    winnerPersonality: "胜者风格",
    playerStatsTitle: "玩家统计",
    statWins: "胜局",
    statDianpao: "点炮次数",
    statBiggestGain: "最大盈",
    statBiggestLoss: "最大亏",
    statSmallHu: "小胡",
    statLargeHu: "大胡",
    statZimo: "自摸",
    statSevenPairs: "七对",
    historyTitle: "对局记录",
    historyDraw: "流局",
    historyZimo: "自摸",
    historyDianpao: (name) => `点炮于${name}`,
    bestRoundLabel: "最大单局收益",
    bestRoundLine: (name, amt, n) => `${name} +${amt}（第${n}局）`,
    bankruptcyTitle: "破产",
    bankruptcyLine: (name, n) => `${name}在第${n}局破产`,
    noBankruptcy: "无人破产。",
    open: "明", hidden: "暗", tiles: "张",
    turnOrder: "逆时针",
    posLeft: "← 左", posRight: "右 →", posAcross: "对面",
    scoreLabel: "分",
    smallHu: "小胡", largeHu: "大胡",
    winTypeZimo: "自摸", winTypeDianpao: "点炮",
    breakdownTitle: "结算",
    baseLabel: "底分",
    modNoOpen: "无明牌",
    modDianpao: "点炮",
    modZimo: "自摸",
    modSevenPairs: "七小对",
    winnerGains: (n) => `胜者 +${n}`,
    loserLoses: (mult, loss) => `×${mult} = -${loss}`,
    logRoundBegin: (n, d) => `第${n}局开始。${d}是庄家。`,
    logExhaust: "流局 — 牌墙摸完！",
    logGangConc: (n, t) => `${n}暗杠${t}。`,
    logZimo: (n, t) => `${n}摸到${t}，自摸胡牌！`,
    logDraw: (n) => `${n}摸了一张牌。`,
    logDiscard: (n, t) => `${n}打出${t}。`,
    logDianpao: (n, t) => `${n}胡了${t}，点炮！`,
    logClaim: (n, t, ty) => `${n}${ty}了${t}。`,
    logYouDraw: (t) => `你摸到了${t}。`,
    logCanHu: "你可以胡牌（自摸）！",
    logYouDiscard: (t) => `你打出了${t}。`,
    logYouHu: "你自摸胡牌！",
    logBadHu: "你的手牌不能胡。",
    logYouGang: (t) => `你暗杠了${t}，补了一张牌。`,
    logYouPromotedGang: (t) => `你加杠了${t}，补了一张牌。`,
    logPromotedGang: (n, t) => `${n}加杠${t}。`,
    promotedGangBtn: (name) => `加杠 (${name})`,
    logOver: "游戏结束！",
    howToPlay: "游戏说明",
    helpClose: "✕ 关闭",
    adminMenuBtn: "🔧 管理",
    adminBtn: "🔧",
    adminTitle: "管理控制台",
    adminClose: "✕ 关闭",
    adminLegend: "牌：b1–b9（条）· c1–c9（万）· d1–d9（饼）· E S W N（风）· R G P（中/發/白）。副露：类型:牌 牌 牌（类型后加!表示暗杠）。多个副露用;分隔。",
    adminMeldExample: "例：peng:c5 c5 c5; chi:b1 b2 b3; gang!:d7 d7 d7 d7",
    adminTurn: "回合",
    adminPhase: "阶段",
    adminWall: "牌墙（下一张）",
    adminScore: "分数",
    adminHand: "手牌",
    adminMelds: "副露",
    adminDiscards: "弃牌",
    adminCancel: "取消",
    adminApply: "应用",
    adminPhaseDraw: "摸牌",
    adminPhaseDiscard: "打牌",
    adminPhaseClaim: "鸣牌",
    adminTabState: "牌局", adminTabNames: "名字",
    manageNamesBtn: "管理名字",
    manageNamesTitle: "电脑玩家名字",
    namesHint: "每局开始时随机选三个名字。列表保存在浏览器中。",
    addNamePlaceholder: "添加名字",
    addNameBtn: "+ 添加",
    addGroupPlaceholder: "新分组名",
    addGroupBtn: "+ 分组",
    resetNamesBtn: "恢复默认",
    namesEmpty: "暂无分组 — 请添加或恢复默认。",
    groupEmpty: "本组无名字。",
    statsBtn: "📊 统计",
    setupTitle: "游戏设置",
    statsTitle: "终身统计",
    statsClose: "✕ 关闭",
    statsSectionGames: "对局",
    statsSectionWins: "胜局与胡牌",
    statsSectionRecords: "纪录",
    statsSectionStreaks: "连胜",
    statsResetBtn: "重置统计",
    statsResetConfirm: "确认重置全部终身统计？无法撤销。",
    statsResetAchievementsBtn: "重置成就",
    statsResetAchievementsConfirm: "确认重置全部已解锁成就？无法撤销。",
    statsSectionAchievements: "成就",
    statsTabStats: "统计",
    statsTabAchievements: "成就",
    achToastUnlocked: (name) => `🏆 解锁成就：${name}`,
    achUnlockedAt: (date) => `解锁于 ${date}`,
    achLocked: "未解锁",
    achFirstHuName: "首胡",
    achFirstHuDesc: "赢得第一局。",
    achFirstLargeHuName: "大胡",
    achFirstLargeHuDesc: "以大胡赢一局。",
    achFirstSevenPairsName: "七小对",
    achFirstSevenPairsDesc: "以七小对赢一局。",
    achFirstZimoName: "自摸",
    achFirstZimoDesc: "自摸赢一局。",
    achWins10Name: "老兵",
    achWins10Desc: "累计胜10局。",
    achWins50Name: "大师",
    achWins50Desc: "累计胜50局。",
    achNoClaimWinName: "自食其力",
    achNoClaimWinDesc: "不吃碰杠胡牌。",
    achBankruptTableName: "桌底",
    achBankruptTableDesc: "三名对手都欠分时结束游戏。",
    achLastTileName: "海底捞月",
    achLastTileDesc: "以牌墙最后一张胡牌。",
    achComebackKidName: "逆袭",
    achComebackKidDesc: "半数轮次处于垫底后赢得整局。",
    achStreak5Name: "火热",
    achStreak5Desc: "连胜5局。",
    achPuristName: "纯粹",
    achPuristDesc: "不使用提示赢得整局。",
    achDailyWin1Name: "每日首胜",
    achDailyWin1Desc: "首次赢得每日挑战。",
    achDailyWinStreak7Name: "周冠",
    achDailyWinStreak7Desc: "连胜7天每日挑战（按UTC计）。",
    dailyChallengeBtn: "🗓 每日",
    dailyChallengeTitle: "每日挑战",
    dailyToday: "今日（UTC）",
    dailyResultLabel: "结果",
    dailyStreakLabel: "连胜",
    dailyDaysFmt: (n) => `${n}天`,
    dailyWon: "胜",
    dailyLost: "负",
    dailyResetIn: (h, m) => `${h}小时${m}分后刷新`,
    dailyAlreadyPlayed: "今日挑战已完成。",
    dailyNotPlayed: "今日挑战可参加。",
    dailyResultWon: "结果：胜",
    dailyResultLost: "结果：负",
    dailyFinalScore: (n) => `终局分数：${n}`,
    dailyRank: (r) => `排名：${r}`,
    dailyStreak: (n) => `当前连胜：${n}天`,
    dailyStartBtn: "开始今日挑战",
    dailyReplayBtn: "再玩一次（不计录）",
    dailyClose: "✕ 关闭",
    dailyNote: "每日使用固定设置（专家·1风圈·禁止提示），以UTC日期作为所有玩家共享的种子。",
    lblGamesPlayed: "总场次",
    lblGamesWon: "胜场",
    lblWinRate: "胜率",
    lblRoundsPlayed: "总局数",
    lblRoundsWon: "胡牌局数",
    lblRoundsDianpao: "点炮次数",
    lblSmallHu: "小胡",
    lblLargeHu: "大胡",
    lblZimoHu: "自摸",
    lblSevenPairsHu: "七小对",
    lblBiggestGain: "单局最大盈",
    lblBiggestLoss: "单局最大亏",
    lblBestBalance: "终局最高分",
    lblWorstBalance: "终局最低分",
    lblTotalNet: "终身净分",
    lblCurrentStreak: "当前连胜",
    lblLongestStreak: "最长连胜",
    statsEmDash: "—",
  },
};
